name: ✨ Feature Request
description: Suggest a new feature or enhancement
title: "[FEATURE]: "
labels: ["enhancement", "triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide as much detail as possible to help us understand your request.

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which component would this feature affect?
      options:
        - Frontend (React)
        - Backend (Node.js)
        - Database (MongoDB)
        - Authentication
        - File Upload
        - Reporting
        - API
        - Documentation
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature?
      options:
        - Critical (Essential for core functionality)
        - High (Significant improvement)
        - Medium (Nice to have)
        - Low (Future consideration)
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: Describe the problem or limitation you're facing...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see
      placeholder: Describe your proposed feature in detail...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Describe any alternative solutions you've considered
      placeholder: What other approaches have you considered?

  - type: textarea
    id: use_cases
    attributes:
      label: Use Cases
      description: Provide specific use cases for this feature
      placeholder: |
        1. As a [user type], I want to [action] so that [benefit]
        2. As a [user type], I want to [action] so that [benefit]
        3. ...

  - type: textarea
    id: acceptance_criteria
    attributes:
      label: Acceptance Criteria
      description: Define what "done" looks like for this feature
      placeholder: |
        - [ ] Criterion 1
        - [ ] Criterion 2
        - [ ] Criterion 3

  - type: textarea
    id: mockups
    attributes:
      label: Mockups/Designs
      description: If applicable, add mockups, wireframes, or design references
      placeholder: Attach images or describe the UI/UX design...

  - type: textarea
    id: technical_considerations
    attributes:
      label: Technical Considerations
      description: Any technical considerations or constraints
      placeholder: Database changes, API modifications, performance impact, etc.

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the feature request
      placeholder: Any additional information that might be helpful...

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues to ensure this is not a duplicate
          required: true
        - label: I have provided all the required information above
          required: true
        - label: I am willing to help implement this feature
          required: false
        - label: I am willing to help test this feature
          required: false
